### ISSUE TITLE
Probleme bei erneutem Login

### ISSUE THREAD

**Issue by sellfisch** [Clerkvest/Clerkvest-API#10]
Wenn man sich einmal eingeloggt hat, und sich auf einem anderen Browser einloggen will. Kann man sich keine neuen Loginlink zuschicken lassen und der alte ist nicht mehr gültig

Bei Sign in kommt die meldung, "Company is invite only. Please contact your administrator."

**Comment by Voxen4** [comment]
Ich kann den Fehler weder Lokal noch im live System reproduzieren, weitere Information wären hilfreich. @sellfisch

**Comment by sellfisch** [comment]
Ist bei uns jetzt bei cai@mobfish und sell@mobfish aufgetreten

Wenn der Login abläuft und man sich neu Einloggen will kann man keinen Link generieren

Reproduizieren:
- Auf Seite gehen
- Sign in 
- sell@mobfish.net eingeben
- dann kommt "Company is invite only. Please contact your administrator."

erwartetes verhalten: Ich bekomme einen neuen Email link
