### ISSUE TITLE
Weiterhin probleme mit login

### ISSUE THREAD

**Issue by sellfisch** [Clerkvest/Clerkvest-API#26]
Login funktioniert nicht:
Also ich kann mich nur neu anmelden
Siehe: https://drive.google.com/file/d/1aIUBHJxxYb3kHjwkl9r9817viPkV1NiX/view?usp=sharing
Das habe ich auch jetzt schon dreimal gemacht. Müsen die mal schauen ob ich da jetzt dreimal als user angelegt bin oder so, video gerne mitschicken. Jeder mit dem Link kann es sehen

**Comment by Voxen4** [comment]
![image](https://user-images.githubusercontent.com/22433896/77324336-e3655b00-6d16-11ea-8e80-e14a5992807d.png)
Serverseitig wird ein Token generiert, der User wird trotzdem nicht weitergeleitet, funktioniert das Setzen der Cookies korrekt? @Qu1oX
Problem hätte eigentlich durch https://github.com/Clerkvest/Clerkvest-App/commit/290ac98c208ef72e9a1f6e67a2e852f6a8bd2c16 gelöst worden sollen.

**Comment by Voxen4** [comment]
### Mail Request & Response
> 2020-03-23 09:46:47.957 TRACE 2680 --- [http-nio-8080-exec-1] org.zalando.logbook.Logbook              : Incoming Request: a4f0d71204d1e316
Remote: 178.254.12.15
POST http://clerkvest.com/api/login?mail=wXXX@mobfish.net HTTP/1.1
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.5
connection: close
content-length: 0
cookie: wpcc=dismiss
host: clerkvest.com
origin: https://clerkvest.com
referer: https://clerkvest.com/?redirected=unknown_user
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0
x-forwarded-for: 91.60.200.144
x-forwarded-proto: https
2020-03-23 09:46:48.453 TRACE 2680 --- [http-nio-8080-exec-1] org.zalando.logbook.Logbook              : Outgoing Response: a4f0d71204d1e316
Duration: 495 ms
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Connection: close
Content-Type: application/json
Date: Mon, 23 Mar 2020 08:46:48 GMT
Transfer-Encoding: chunked
Vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
{"response":"E-Mail Sent Successfully"}

### Login Request & Response
> 2020-03-23 09:47:16.113 TRACE 2680 --- [http-nio-8080-exec-3] org.zalando.logbook.Logbook              : Incoming Request: f32debd3c353be34
Remote: 178.254.12.15
GET http://clerkvest.com/api/token/XXX HTTP/1.1
accept: application/json
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.5
connection: close
cookie: wpcc=dismiss
host: clerkvest.com
referer: https://clerkvest.com/app/login/XXX
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0
x-forwarded-for: 91.60.200.144
x-forwarded-proto: https
2020-03-23 09:47:16.124 TRACE 2680 --- [http-nio-8080-exec-3] org.zalando.logbook.Logbook              : Outgoing Response: f32debd3c353be34
Duration: 10 ms
HTTP/1.1 200 OK
Connection: close
Content-Type: application/json
Date: Mon, 23 Mar 2020 08:47:16 GMT
Transfer-Encoding: chunked
Vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers

{"response":"XXXNEWTOKEN"}

**Comment by Qu1oX** [comment]
@sellfisch Wir haben die Datenbank gespiegelt und Local mit seinen Daten getestet. Dabei hat alles wie geplant funktioniert. Demnach denken wir, dass Firefox die Cookies nicht speichert. Kann dein Mitarbeiter vllt. einmal die Console sowie Cookies Fotografieren?

Sollte in etwas so aussehen: 
![firefox_ns6YX8Kyap](https://user-images.githubusercontent.com/25693070/77343492-0e10dd00-6d32-11ea-8f07-a19ebb2621e9.png)
![firefox_rcTo9HfYlv](https://user-images.githubusercontent.com/25693070/77343500-0fdaa080-6d32-11ea-8624-29fa48ad30d5.png)
